name: Schedule Commit
on:
  schedule:
    - cron: '41 12 * * *' # Runs at 12:41 PM UTC every day
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make changes
        run: |
          # Your script to make changes
          echo "New commit at $(date)" >> changes.txt

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "daniumy"
          git config --global user.email "daniumy@protonmail.com"
          git add .
          git commit -m "Scheduled commit"
          git push
